version: "3"
services:
  nextcloud:
    init: true
    container_name: nextcloud-aio-mastercontainer
    image: nextcloud/all-in-one:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=0.0.0.0
      - APACHE_ADDITIONAL_NETWORK
      - SKIP_DOMAIN_VALIDATION=false
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
  nginx:
    container_name: nginx
    image: nginx:1.27.4
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./production/default.nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - ./production/dhparam:/etc/dhparam

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer